import { Champion } from "./types";

// A simplified list of champions. In a real production app, this might come from Riot's Data Dragon API.
export const CHAMPIONS: Champion[] = [
    { id: "aatrox", name: "Aatrox", title: "a Espada Darkin" },
    { id: "ahri", name: "Ahri", title: "a Raposa de Nove Caudas" },
    { id: "akali", name: "Akali", title: "a Assassina Renegada" },
    { id: "akshan", name: "Akshan", title: "o Sentinela Rebelde" },
    { id: "alistar", name: "Alistar", title: "o Minotauro" },
    { id: "ambessa", name: "Ambessa", title: "a Matriarca da Guerra" },
    { id: "amumu", name: "Amumu", title: "a Múmia Triste" },
    { id: "anivia", name: "Anivia", title: "a Criofênix" },
    { id: "annie", name: "Annie", title: "a Criança Sombria" },
    { id: "aphelios", name: "Aphelios", title: "a Arma dos Devotos" },
    { id: "ashe", name: "Ashe", title: "a Arqueira do Gelo" },
    { id: "aurelionsol", name: "Aurelion Sol", title: "o Forjador de Estrelas" },
    { id: "aurora", name: "Aurora", title: "a Bruxa Entre Mundos" },
    { id: "azir", name: "Azir", title: "o Imperador das Areias" },
    { id: "bard", name: "Bardo", title: "o Protetor Andarilho" },
    { id: "belveth", name: "Bel'Veth", title: "a Imperatriz do Vazio" },
    { id: "blitzcrank", name: "Blitzcrank", title: "o Grande Golem a Vapor" },
    { id: "brand", name: "Brand", title: "a Vingança Flamejante" },
    { id: "braum", name: "Braum", title: "o Coração de Freljord" },
    { id: "briar", name: "Briar", title: "a Fome Contida" },
    { id: "caitlyn", name: "Caitlyn", title: "a Xerife de Piltover" },
    { id: "camille", name: "Camille", title: "a Sombra de Aço" },
    { id: "cassiopeia", name: "Cassiopeia", title: "o Abraço da Serpente" },
    { id: "chogath", name: "Cho'Gath", title: "o Terror do Vazio" },
    { id: "corki", name: "Corki", title: "o Bombardeiro Ousado" },
    { id: "darius", name: "Darius", title: "a Mão de Noxus" },
    { id: "diana", name: "Diana", title: "o Escárnio da Lua" },
    { id: "drmundo", name: "Dr. Mundo", title: "o Louco de Zaun" },
    { id: "draven", name: "Draven", title: "o Carrasco de Noxus" },
    { id: "ekko", name: "Ekko", title: "o Rapaz que Estilhaçou o Tempo" },
    { id: "elise", name: "Elise", title: "a Rainha Aranha" },
    { id: "evelynn", name: "Evelynn", title: "o Abraço da Agonia" },
    { id: "ezreal", name: "Ezreal", title: "o Explorador Pródigo" },
    { id: "fiddlesticks", name: "Fiddlesticks", title: "o Terror Ancestral" },
    { id: "fiora", name: "Fiora", title: "a Grande Duelista" },
    { id: "fizz", name: "Fizz", title: "o Trapaceiro das Marés" },
    { id: "galio", name: "Galio", title: "o Colosso" },
    { id: "gangplank", name: "Gangplank", title: "o Terror dos Doze Mares" },
    { id: "garen", name: "Garen", title: "o Poder de Demacia" },
    { id: "gnar", name: "Gnar", title: "o Yordle Pré-Histórico" },
    { id: "gragas", name: "Gragas", title: "o Badernista" },
    { id: "graves", name: "Graves", title: "o Foragido" },
    { id: "gwen", name: "Gwen", title: "a Costureira Encantada" },
    { id: "hecarim", name: "Hecarim", title: "a Sombra da Guerra" },
    { id: "heimerdinger", name: "Heimerdinger", title: "o Inventor Idolatrado" },
    { id: "hwei", name: "Hwei", title: "o Visionário" },
    { id: "illaoi", name: "Illaoi", title: "a Sacerdotisa Cráquem" },
    { id: "irelia", name: "Irelia", title: "a Dançarina das Lâminas" },
    { id: "ivern", name: "Ivern", title: "o Pai do Verde" },
    { id: "janna", name: "Janna", title: "a Fúria da Tormenta" },
    { id: "jarvaniv", name: "Jarvan IV", title: "o Exemplo de Demacia" },
    { id: "jax", name: "Jax", title: "o Grão-Mestre das Armas" },
    { id: "jayce", name: "Jayce", title: "o Defensor do Amanhã" },
    { id: "jhin", name: "Jhin", title: "o Virtuoso" },
    { id: "jinx", name: "Jinx", title: "o Gatilho Desenfreado" },
    { id: "kaisa", name: "Kai'Sa", title: "a Filha do Vazio" },
    { id: "kalista", name: "Kalista", title: "a Lança da Vingança" },
    { id: "karma", name: "Karma", title: "a Iluminada" },
    { id: "karthus", name: "Karthus", title: "a Voz Mortal" },
    { id: "kassadin", name: "Kassadin", title: "o Andarilho do Vazio" },
    { id: "katarina", name: "Katarina", title: "a Lâmina Sinistra" },
    { id: "kayle", name: "Kayle", title: "a Justa" },
    { id: "kayn", name: "Kayn", title: "o Ceifador das Sombras" },
    { id: "kennen", name: "Kennen", title: "o Coração da Tempestade" },
    { id: "khazix", name: "Kha'Zix", title: "o Ceifador do Vazio" },
    { id: "kindred", name: "Kindred", title: "os Caçadores Eternos" },
    { id: "kled", name: "Kled", title: "o Cavaleiro Intratável" },
    { id: "kogmaw", name: "Kog'Maw", title: "a Boca do Abismo" },
    { id: "ksante", name: "K'Sante", title: "o Orgulho de Nazumah" },
    { id: "leblanc", name: "LeBlanc", title: "a Farsante" },
    { id: "leesin", name: "Lee Sin", title: "o Monge Cego" },
    { id: "leona", name: "Leona", title: "a Alvorada Radiante" },
    { id: "lillia", name: "Lillia", title: "o Florir Receoso" },
    { id: "lissandra", name: "Lissandra", title: "a Bruxa Gélida" },
    { id: "lucian", name: "Lucian", title: "o Purificador" },
    { id: "lulu", name: "Lulu", title: "a Fada Feiticeira" },
    { id: "lux", name: "Lux", title: "a Dama da Luz" },
    { id: "malphite", name: "Malphite", title: "o Fragmento do Monólito" },
    { id: "malzahar", name: "Malzahar", title: "o Profeta do Vazio" },
    { id: "maokai", name: "Maokai", title: "o Ente Distorcido" },
    { id: "masteryi", name: "Master Yi", title: "o Espadachim Wuju" },
    { id: "mel", name: "Mel", title: "a Mão Dourada" },
    { id: "milio", name: "Milio", title: "a Chama Gentil" },
    { id: "missfortune", name: "Miss Fortune", title: "a Caçadora de Recompensas" },
    { id: "mordekaiser", name: "Mordekaiser", title: "o Revenã de Ferro" },
    { id: "morgana", name: "Morgana", title: "a Caída" },
    { id: "naafiri", name: "Naafiri", title: "a Fera das Cem Mordidas" },
    { id: "nami", name: "Nami", title: "a Conjuradora das Marés" },
    { id: "nasus", name: "Nasus", title: "o Curador das Areias" },
    { id: "nautilus", name: "Nautilus", title: "o Titã das Profundezas" },
    { id: "neeko", name: "Neeko", title: "a Camaleoa Curiosa" },
    { id: "nidalee", name: "Nidalee", title: "a Caçadora Bestial" },
    { id: "nilah", name: "Nilah", title: "a Alegria Desencarnada" },
    { id: "nocturne", name: "Nocturne", title: "o Eterno Pesadelo" },
    { id: "nunu", name: "Nunu & Willump", title: "o Garoto e seu Yeti" },
    { id: "olaf", name: "Olaf", title: "o Berserker" },
    { id: "orianna", name: "Orianna", title: "a Donzela Mecânica" },
    { id: "ornn", name: "Ornn", title: "o Fogo sob a Montanha" },
    { id: "pantheon", name: "Pantheon", title: "a Lança Indestrutível" },
    { id: "poppy", name: "Poppy", title: "a Guardiã do Martelo" },
    { id: "pyke", name: "Pyke", title: "o Estripador das Águas Sangrentas" },
    { id: "qiyana", name: "Qiyana", title: "a Imperatriz dos Elementos" },
    { id: "quinn", name: "Quinn", title: "as Asas de Demacia" },
    { id: "rakan", name: "Rakan", title: "o Charmoso" },
    { id: "rammus", name: "Rammus", title: "o Tatu Blindado" },
    { id: "reksai", name: "Rek'Sai", title: "a Escavadora do Vazio" },
    { id: "rell", name: "Rell", title: "a Dama de Ferro" },
    { id: "renata", name: "Renata Glasc", title: "a Baronesa da Química" },
    { id: "renekton", name: "Renekton", title: "o Carniceiro das Areias" },
    { id: "rengar", name: "Rengar", title: "o Acossador da Alcateia" },
    { id: "riven", name: "Riven", title: "a Exilada" },
    { id: "rumble", name: "Rumble", title: "a Ameaça Mecânica" },
    { id: "ryze", name: "Ryze", title: "o Mago Rúnico" },
    { id: "samira", name: "Samira", title: "a Rosa do Deserto" },
    { id: "sejuani", name: "Sejuani", title: "a Fúria do Norte" },
    { id: "senna", name: "Senna", title: "a Redentora" },
    { id: "seraphine", name: "Seraphine", title: "a Cantora Sonhadora" },
    { id: "sett", name: "Sett", title: "o Chefe" },
    { id: "shaco", name: "Shaco", title: "o Bufão Demoníaco" },
    { id: "shen", name: "Shen", title: "o Olho do Crepúsculo" },
    { id: "shyvana", name: "Shyvana", title: "o Meio-Dragão" },
    { id: "singed", name: "Singed", title: "o Químico Louco" },
    { id: "sion", name: "Sion", title: "o Colosso Morto-Vivo" },
    { id: "sivir", name: "Sivir", title: "a Mestra da Batalha" },
    { id: "skarner", name: "Skarner", title: "o Soberano Primordial" },
    { id: "smolder", name: "Smolder", title: "o Filhote Flamejante" },
    { id: "sona", name: "Sona", title: "a Mestra das Cordas" },
    { id: "soraka", name: "Soraka", title: "a Filha das Estrelas" },
    { id: "swain", name: "Swain", title: "o Grande General Noxiano" },
    { id: "sylas", name: "Sylas", title: "o Abjugado" },
    { id: "syndra", name: "Syndra", title: "a Soberana Sombria" },
    { id: "tahmkench", name: "Tahm Kench", title: "o Rei do Rio" },
    { id: "taliyah", name: "Taliyah", title: "a Tecelã de Pedras" },
    { id: "talon", name: "Talon", title: "a Sombra da Lâmina" },
    { id: "taric", name: "Taric", title: "o Escudo de Valoran" },
    { id: "teemo", name: "Teemo", title: "o Explorador Veloz" },
    { id: "thresh", name: "Thresh", title: "o Guardião das Correntes" },
    { id: "tristana", name: "Tristana", title: "a Artilheira Yordle" },
    { id: "trundle", name: "Trundle", title: "o Rei dos Trolls" },
    { id: "tryndamere", name: "Tryndamere", title: "o Rei Bárbaro" },
    { id: "twistedfate", name: "Twisted Fate", title: "o Mestre das Cartas" },
    { id: "twitch", name: "Twitch", title: "o Semeador da Peste" },
    { id: "udyr", name: "Udyr", title: "o Andarilho Espiritual" },
    { id: "urgot", name: "Urgot", title: "o Encouraçado" },
    { id: "varus", name: "Varus", title: "a Flecha da Vingança" },
    { id: "vayne", name: "Vayne", title: "a Caçadora Noturna" },
    { id: "veigar", name: "Veigar", title: "o Pequeno Mestre do Mal" },
    { id: "velkoz", name: "Vel'Koz", title: "o Olho do Vazio" },
    { id: "vex", name: "Vex", title: "a Melancolista" },
    { id: "vi", name: "Vi", title: "a Defensora de Piltover" },
    { id: "viego", name: "Viego", title: "o Rei Destruído" },
    { id: "viktor", name: "Viktor", title: "o Arauto das Máquinas" },
    { id: "vladimir", name: "Vladimir", title: "o Sanguinário Escarlate" },
    { id: "volibear", name: "Volibear", title: "a Tempestade Implacável" },
    { id: "warwick", name: "Warwick", title: "a Ira Desimpedida de Zaun" },
    { id: "wukong", name: "Wukong", title: "o Macaco Rei" },
    { id: "xayah", name: "Xayah", title: "a Rebelde" },
    { id: "xerath", name: "Xerath", title: "o Mago Ascendente" },
    { id: "xinzhao", name: "Xin Zhao", title: "o Senescal de Demacia" },
    { id: "yasuo", name: "Yasuo", title: "o Imperdoável" },
    { id: "yone", name: "Yone", title: "o Inesquecido" },
    { id: "yorick", name: "Yorick", title: "o Pastor de Almas" },
    { id: "yuumi", name: "Yuumi", title: "a Gata Mágica" },
    { id: "zac", name: "Zac", title: "a Arma Secreta" },
    { id: "zed", name: "Zed", title: "o Mestre das Sombras" },
    { id: "zeri", name: "Zeri", title: "a Faísca de Zaun" },
    { id: "ziggs", name: "Ziggs", title: "o Especialista em Hexplosivos" },
    { id: "zilean", name: "Zilean", title: "o Guardião do Tempo" },
    { id: "zoe", name: "Zoe", title: "o Aspecto do Crepúsculo" },
    { id: "zyra", name: "Zyra", title: "a Ascensão dos Espinhos" }
];